apiVersion: 1

datasources:
  - name: prom-01
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prom-01:9090
    isDefault: false
    version: 1
    editable: true
    
  - name: Cortex
    type: prometheus
    access: proxy
    url: http://cortex-01:9009/prometheus
    isDefault: true
    version: 1
    editable: true
