groups:
- name: example
  rules:
  - alert: service_down
    expr: up == 0
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down."
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5s."
