global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
rule_files:
  - alerts.yaml
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    api_version: v2
    static_configs:
    - targets:
      - am-01:9093
      - am-02:9093
      - am-03:9093
scrape_configs:
- job_name: alertmanager
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - am-01:9093
    - am-02:9093
    - am-03:9093
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - prom-01:9090
    - prom-02:9090
