global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    replica: prom-01
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - am-01:9093
scrape_configs:
- job_name: alertmanager
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - am-01:9093
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - prom-01:9090
    - prom-02:9090
- job_name: thanos
  scrape_interval: 5s
  static_configs:
  - targets:
    - prom-01-sidecar:10902
    - prom-01-sidecar:10902
    - querier-01:10902
    - store-gateway-01:10902
- job_name: minio
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - minio-01:10902
