--- 
version: "3.8"
services: 
  store-01: 
    command: "-c 'mkdir -p /data/demo-bucket && /usr/bin/minio server /data'"
    entrypoint: sh
    environment: 
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    image: "minio/minio:RELEASE.2020-05-01T22-19-14Z"
    ports: 
      - "9000:9000"
    volumes: 
      - "store-01-persistence:/data"
  node-exporter: 
    command: 
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    image: "prom/node-exporter:v1.2.2"
    ports: 
      - "9100:9100"
    restart: always
    volumes: 
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
  gw-01: 
    command: 
      - store
      - "--grpc-address=0.0.0.0:10091"
      - "--http-address=0.0.0.0:10902"
      - "--data-dir=/tmp/thanos/store"
      - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
    depends_on: 
      - store-01
    image: "quay.io/thanos/thanos:v0.22.0"
    restart: always
    volumes: 
      - "./thanos/:/etc/thanos/"
volumes:
  grafana-01-persistence: {}
  store-01-persistence: {}