version: "3"
services:
    haproxy:
      image: haproxy:2.0.5-alpine
      volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      ports:
      - "8404:8404"
      - "9009:9009"
    consul:
      image: consul
      command: --log.level=warn
      ports:
      - "8500:8500"
    cortex1:
      image: cortexproject/cortex:master-7d13c2f0
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500 --log.level=warn
      depends_on:
        - consul
      ports:
      - "9001:9009"
      volumes:
      - "./cortex/single-process-config.yaml:/etc/single-process-config.yaml"
    cortex2:
      image: cortexproject/cortex:master-7d13c2f0
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500 --log.level=warn
      depends_on:
        - consul
      ports:
      - "9002:9009"
      volumes:
      - "./cortex/single-process-config.yaml:/etc/single-process-config.yaml"
    cortex3:
      image: cortexproject/cortex:master-7d13c2f0
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500 --log.level=warn
      depends_on:
        - consul
      ports:
      - "9003:9009"
      volumes:
      - "./cortex/single-process-config.yaml:/etc/single-process-config.yaml"
    grafana:
      image: grafana/grafana
      ports:
      - "3000:3000"
    node-exporter:
      image: basi/node-exporter
      ports:
      - "9100:9100"
    prometheus:
      image: prom/prometheus
      depends_on:
        - cortex1
        - cortex2
        - cortex3
      ports:
      - "9090:9090"
      volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      
      