apiVersion: v1
kind: ConfigMap
metadata:
  name: promxy-config
data:
  config.yaml: |
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    promxy:
      server_groups:
        - kubernetes_sd_configs:
          - role: pod

