---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |+
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'lisboa'
        replica: 'a1'
    scrape_configs:
      #TODO use service discovery
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus:9090']
