apiVersion: v1
kind: Service
metadata:
  name: promxy
  labels:
    app: promxy
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: web
      protocol: TCP
      name: lb-promxy
  selector:
    app: promxy
