apiVersion: apps/v1
kind: Deployment
metadata:
  name: promxy
  labels:
    app: promxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      containers:
      - name: promxy
        image: quay.io/jacksontj/promxy:v0.0.75
        args:
        - --config=/cmd/promxy/config.yaml
        - --log-level=warn
        - --web.enable-lifecycle
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: promxy-config
          mountPath: /cmd/promxy/      
      volumes:
      - name: promxy-config
        configMap:
          name: promxy-config
