apiVersion: v1
kind: ConfigMap
metadata:
  name: promxy-config
data:
  config.yaml: |
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    promxy:
      server_groups:
        # - kubernetes_sd_configs:
        #    - role: pod
        #   namespaces:
        #     names:
        #     - default
        - static_configs:
            - targets:
              - localhost:9090
          labels:
            sg: localhost_9090
          anti_affinity: 10s
          remote_read: true
          path_prefix: /example/prefix
          query_params:
            nocache: 1
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
          relative_time_range:
            start: -3h
            end: -1h
            truncate: false
          ignore_error: true
